file = open("C:\\Users\\99003729\\Desktop\\project.txt", "r")
print("Reading initial contents")
print(file.read())
print("finished")
file.close()

file = open("C:\\Users\\99003729\\Desktop\\project.txt", "w")
file.write("some new text")
file.close()

file = open("C:\\Users\\99003729\\Desktop\\project.txt", "r")
print("reading new content")
print(file.read())
print("finished")
file.close()